apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: trainapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: trainapp 
    spec:
      containers:
        - name: trainapp 
          image: trainapp.azurecr.io/trainapp
          ports:
          - containerPort: 8080